import {
  Code2,
  Hash,
  Palette,
  FileText,
  Lock,
  Link,
  Clock,
  Ruler,
  Binary,
  Calculator,
  QrCode,
} from 'lucide-react';
import type { Tool } from '../types';

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data',
    icon: Code2,
    path: '/tool/json-formatter',
    category: 'Formatters',
    keywords: ['json', 'format', 'beautify', 'validate', 'minify', 'pretty print'],
  },
  {
    id: 'url-encoder-decoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL strings',
    icon: Link,
    path: '/tool/url-encoder-decoder',
    category: 'Encoders',
    keywords: ['url', 'encode', 'decode', 'uri', 'percent encoding'],
  },
  {
    id: 'base64-converter',
    name: 'Base64 Converter',
    description: 'Encode and decode Base64 strings',
    icon: Binary,
    path: '/tool/base64-converter',
    category: 'Encoders',
    keywords: ['base64', 'encode', 'decode', 'converter'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, and other hashes',
    icon: Hash,
    path: '/tool/hash-generator',
    category: 'Cryptography',
    keywords: ['hash', 'md5', 'sha', 'sha1', 'sha256', 'checksum'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL, and other color formats',
    icon: Palette,
    path: '/tool/color-converter',
    category: 'Utilities',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'converter', 'picker'],
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Live markdown editor with preview',
    icon: FileText,
    path: '/tool/markdown-preview',
    category: 'Formatters',
    keywords: ['markdown', 'md', 'preview', 'editor', 'live'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUIDs (v1, v4)',
    icon: Lock,
    path: '/tool/uuid-generator',
    category: 'Generators',
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between timestamps and dates',
    icon: Clock,
    path: '/tool/timestamp-converter',
    category: 'Utilities',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'converter'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions',
    icon: Ruler,
    path: '/tool/regex-tester',
    category: 'Utilities',
    keywords: ['regex', 'regexp', 'regular expression', 'test', 'match'],
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert between binary, decimal, hex, and octal',
    icon: Calculator,
    path: '/tool/number-base-converter',
    category: 'Utilities',
    keywords: ['binary', 'decimal', 'hex', 'octal', 'converter', 'base'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens',
    icon: Lock,
    path: '/tool/jwt-decoder',
    category: 'Cryptography',
    keywords: ['jwt', 'json web token', 'decode', 'inspect', 'token'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text',
    icon: QrCode,
    path: '/tool/qr-generator',
    category: 'Generators',
    keywords: ['qr', 'qr code', 'generate', 'barcode'],
  },
];

export const categories = [
  { id: 'all', name: 'All Tools', description: 'Browse all available tools' },
  { id: 'Formatters', name: 'Formatters', description: 'Format and beautify code and data' },
  { id: 'Encoders', name: 'Encoders', description: 'Encode and decode various formats' },
  { id: 'Cryptography', name: 'Cryptography', description: 'Hashing and cryptographic tools' },
  { id: 'Utilities', name: 'Utilities', description: 'General utility tools' },
  { id: 'Generators', name: 'Generators', description: 'Generate IDs, codes, and more' },
];
