import {
  Code2,
  Hash,
  Palette,
  FileText,
  Lock,
  Link,
  Clock,
  Binary,
  Key,
  Type,
  FileDigit,
  Text,
  Shuffle,
  Copy as CopyIcon,
  GitCompare,
  CheckCircle,
  Minimize2,
  Image,
  Link2,
  Smile,
  Replace,
  Table,
  FileJson,
  Droplet,
  Box,
  CornerDownRight,
  Calculator,
  Ruler,
  IndianRupee,
  Cake,
  CalendarDays,
  Briefcase,
  Receipt,
  Activity,
  SpellCheck,
  WrapText,
  ListOrdered,
} from 'lucide-react';
import type { Tool } from '../types';

export const tools: Tool[] = [
  // Formatters & Validators
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data',
    icon: Code2,
    path: '/tool/json-formatter',
    category: 'Formatters',
    keywords: ['json', 'format', 'beautify', 'validate', 'minify', 'pretty print'],
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    description: 'Minify JSON and reduce file size',
    icon: Minimize2,
    path: '/tool/json-minifier',
    category: 'Formatters',
    keywords: ['json', 'minify', 'compress', 'reduce', 'size'],
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate JSON structure and syntax',
    icon: CheckCircle,
    path: '/tool/json-validator',
    category: 'Formatters',
    keywords: ['json', 'validate', 'check', 'syntax', 'structure'],
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Live markdown editor with preview',
    icon: FileText,
    path: '/tool/markdown-preview',
    category: 'Formatters',
    keywords: ['markdown', 'md', 'preview', 'editor', 'live'],
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data to JSON format',
    icon: Table,
    path: '/tool/csv-to-json',
    category: 'Converters',
    keywords: ['csv', 'json', 'convert', 'transform', 'data'],
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON array to CSV format',
    icon: FileJson,
    path: '/tool/json-to-csv',
    category: 'Converters',
    keywords: ['json', 'csv', 'convert', 'export', 'excel'],
  },
  
  // Encoders & Decoders
  {
    id: 'url-encoder-decoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL strings',
    icon: Link,
    path: '/tool/url-encoder-decoder',
    category: 'Encoders',
    keywords: ['url', 'encode', 'decode', 'uri', 'percent encoding'],
  },
  {
    id: 'base64-converter',
    name: 'Base64 Converter',
    description: 'Encode and decode Base64 strings',
    icon: Binary,
    path: '/tool/base64-converter',
    category: 'Encoders',
    keywords: ['base64', 'encode', 'decode', 'converter'],
  },
  {
    id: 'html-encoder-decoder',
    name: 'HTML Encoder/Decoder',
    description: 'Encode and decode HTML entities',
    icon: Code2,
    path: '/tool/html-encoder-decoder',
    category: 'Encoders',
    keywords: ['html', 'encode', 'decode', 'entities', 'escape'],
  },
  {
    id: 'base64-image',
    name: 'Base64 Image Converter',
    description: 'Convert images to Base64 and vice versa',
    icon: Image,
    path: '/tool/base64-image',
    category: 'Encoders',
    keywords: ['base64', 'image', 'convert', 'encode', 'decode', 'data uri'],
  },
  
  // Security & Cryptography
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, and other hashes',
    icon: Hash,
    path: '/tool/hash-generator',
    category: 'Security',
    keywords: ['hash', 'md5', 'sha', 'sha1', 'sha256', 'checksum'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens',
    icon: Lock,
    path: '/tool/jwt-decoder',
    category: 'Security',
    keywords: ['jwt', 'json web token', 'decode', 'inspect', 'token'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords',
    icon: Key,
    path: '/tool/password-generator',
    category: 'Security',
    keywords: ['password', 'generate', 'random', 'secure', 'strength'],
  },
  {
    id: 'api-key-generator',
    name: 'API Key Generator',
    description: 'Generate secure API keys',
    icon: Key,
    path: '/tool/api-key-generator',
    category: 'Security',
    keywords: ['api', 'key', 'generate', 'token', 'secure'],
  },
  
  // Time & Date
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between timestamps and dates',
    icon: Clock,
    path: '/tool/timestamp-converter',
    category: 'Time & Date',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'converter'],
  },
  
  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUIDs (v1, v4)',
    icon: Lock,
    path: '/tool/uuid-generator',
    category: 'Generators',
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text',
    icon: Text,
    path: '/tool/lorem-ipsum',
    category: 'Generators',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generate', 'dummy'],
  },
  {
    id: 'url-slug-generator',
    name: 'URL Slug Generator',
    description: 'Generate SEO-friendly URL slugs',
    icon: Link2,
    path: '/tool/url-slug-generator',
    category: 'Generators',
    keywords: ['slug', 'url', 'seo', 'friendly', 'generate'],
  },
  
  // Text Tools
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between different case formats',
    icon: Type,
    path: '/tool/case-converter',
    category: 'Text Tools',
    keywords: ['case', 'convert', 'upper', 'lower', 'camel', 'snake', 'kebab'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, lines, and more',
    icon: FileDigit,
    path: '/tool/word-counter',
    category: 'Text Tools',
    keywords: ['word', 'count', 'character', 'line', 'statistics'],
  },
  {
    id: 'line-sorter',
    name: 'Line Sorter',
    description: 'Sort, reverse, or shuffle text lines',
    icon: Shuffle,
    path: '/tool/line-sorter',
    category: 'Text Tools',
    keywords: ['sort', 'lines', 'alphabetical', 'reverse', 'shuffle'],
  },
  {
    id: 'duplicate-lines',
    name: 'Duplicate Lines Handler',
    description: 'Find and remove duplicate lines',
    icon: CopyIcon,
    path: '/tool/duplicate-lines',
    category: 'Text Tools',
    keywords: ['duplicate', 'lines', 'remove', 'unique', 'deduplicate'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and see differences',
    icon: GitCompare,
    path: '/tool/text-diff',
    category: 'QA & Compare',
    keywords: ['diff', 'compare', 'text', 'difference', 'changes'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff Checker',
    description: 'Compare two JSON objects and see differences',
    icon: GitCompare,
    path: '/tool/json-diff',
    category: 'QA & Compare',
    keywords: ['json', 'diff', 'compare', 'difference', 'changes'],
  },
  {
    id: 'emoji-unicode',
    name: 'Emoji ⇄ Unicode',
    description: 'Convert between emoji and Unicode',
    icon: Smile,
    path: '/tool/emoji-unicode',
    category: 'Text Tools',
    keywords: ['emoji', 'unicode', 'convert', 'code point'],
  },
  {
    id: 'find-replace',
    name: 'Find & Replace',
    description: 'Find and replace text with regex support',
    icon: Replace,
    path: '/tool/find-replace',
    category: 'Text Tools',
    keywords: ['find', 'replace', 'search', 'regex', 'text'],
  },
  {
    id: 'grammar-checker',
    name: 'Grammar & Spell Checker',
    description: 'Check grammar, spelling, and punctuation',
    icon: SpellCheck,
    path: '/tool/grammar-checker',
    category: 'Text Tools',
    keywords: ['grammar', 'spell', 'check', 'punctuation', 'writing', 'text'],
  },
  {
    id: 'remove-line-breaks',
    name: 'Remove Line Breaks',
    description: 'Remove or replace line breaks from text',
    icon: WrapText,
    path: '/tool/remove-line-breaks',
    category: 'Text Tools',
    keywords: ['line', 'breaks', 'remove', 'replace', 'text', 'format'],
  },
  {
    id: 'add-line-numbers',
    name: 'Add Line Numbers',
    description: 'Add line numbers to text with formatting options',
    icon: ListOrdered,
    path: '/tool/add-line-numbers',
    category: 'Text Tools',
    keywords: ['line', 'numbers', 'add', 'format', 'text', 'list'],
  },
  
  // CSS Generators
  {
    id: 'css-generator',
    name: 'CSS Generator',
    description: 'Generate CSS code for styles',
    icon: Droplet,
    path: '/tool/css-generator',
    category: 'CSS Generators',
    keywords: ['css', 'generator', 'styles', 'code', 'create'],
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS code and reduce file size',
    icon: Minimize2,
    path: '/tool/css-minifier',
    category: 'Minifiers',
    keywords: ['css', 'minify', 'compress', 'reduce', 'size'],
  },
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    description: 'Minify HTML code and reduce file size',
    icon: Minimize2,
    path: '/tool/html-minifier',
    category: 'Minifiers',
    keywords: ['html', 'minify', 'compress', 'reduce', 'size'],
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify JavaScript code and reduce file size',
    icon: Minimize2,
    path: '/tool/js-minifier',
    category: 'Minifiers',
    keywords: ['javascript', 'js', 'minify', 'compress', 'reduce', 'size'],
  },
  
  // CSS Generators
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create CSS gradients with live preview',
    icon: Droplet,
    path: '/tool/gradient-generator',
    category: 'CSS Generators',
    keywords: ['css', 'gradient', 'linear', 'radial', 'generator', 'color'],
  },
  {
    id: 'box-shadow-generator',
    name: 'Box Shadow Generator',
    description: 'Generate CSS box shadows',
    icon: Box,
    path: '/tool/box-shadow-generator',
    category: 'CSS Generators',
    keywords: ['css', 'box', 'shadow', 'generator', 'effect'],
  },
  {
    id: 'border-radius-generator',
    name: 'Border Radius Generator',
    description: 'Create custom border radius',
    icon: CornerDownRight,
    path: '/tool/border-radius-generator',
    category: 'CSS Generators',
    keywords: ['css', 'border', 'radius', 'rounded', 'corners'],
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes',
    icon: Palette,
    path: '/tool/color-palette-generator',
    category: 'CSS Generators',
    keywords: ['color', 'palette', 'harmony', 'scheme', 'generator'],
  },

  // Calculators
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages and percentage changes',
    icon: Calculator,
    path: '/tool/percentage-calculator',
    category: 'Calculators',
    keywords: ['percentage', 'percent', 'calculator', 'math'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units of measurement',
    icon: Ruler,
    path: '/tool/unit-converter',
    category: 'Calculators',
    keywords: ['unit', 'convert', 'measurement', 'length', 'weight', 'temperature'],
  },
  {
    id: 'currency-formatter',
    name: 'Currency Formatter',
    description: 'Format numbers as currency with locale support',
    icon: IndianRupee,
    path: '/tool/currency-formatter',
    category: 'Calculators',
    keywords: ['currency', 'money', 'format', 'rupee', 'inr', 'formatter'],
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate age and time between dates',
    icon: Cake,
    path: '/tool/age-calculator',
    category: 'Calculators',
    keywords: ['age', 'birthday', 'calculator', 'date', 'years'],
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Add or subtract time from dates',
    icon: CalendarDays,
    path: '/tool/date-calculator',
    category: 'Calculators',
    keywords: ['date', 'calculator', 'add', 'subtract', 'difference'],
  },
  {
    id: 'business-days-calculator',
    name: 'Business Days Calculator',
    description: 'Calculate business days between dates',
    icon: Briefcase,
    path: '/tool/business-days-calculator',
    category: 'Calculators',
    keywords: ['business', 'days', 'calculator', 'working', 'weekday'],
  },
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate tips and split bills',
    icon: Receipt,
    path: '/tool/tip-calculator',
    category: 'Calculators',
    keywords: ['tip', 'calculator', 'gratuity', 'bill', 'restaurant'],
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index',
    icon: Activity,
    path: '/tool/bmi-calculator',
    category: 'Calculators',
    keywords: ['bmi', 'body', 'mass', 'index', 'health', 'weight'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units of measurement',
    icon: Ruler,
    path: '/tool/unit-converter',
    category: 'Utilities',
    keywords: ['unit', 'converter', 'measurement', 'length', 'area', 'volume'],
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between different currencies',
    icon: IndianRupee,
    path: '/tool/currency-converter',
    category: 'Calculators',
    keywords: ['currency', 'converter', 'exchange', 'rate', 'money', 'rupee', 'inr'],
  },
  {
    id: 'loan-calculator',
    name: 'Loan Calculator',
    description: 'Calculate loan payments and interest',
    icon: Briefcase,
    path: '/tool/loan-calculator',
    category: 'Calculators',
    keywords: ['loan', 'calculator', 'payment', 'interest', 'mortgage', 'emi'],
  },
  {
    id: 'calorie-calculator',
    name: 'Calorie Calculator',
    description: 'Calculate calorie intake and expenditure',
    icon: Activity,
    path: '/tool/calorie-calculator',
    category: 'Calculators',
    keywords: ['calorie', 'calculator', 'diet', 'nutrition', 'fitness', 'health'],
  },
];

export const categories = [
  { id: 'all', name: 'All Tools', description: 'Browse all available tools' },
  { id: 'Formatters', name: 'Formatters', description: 'Format and beautify code and data' },
  { id: 'Encoders', name: 'Encoders', description: 'Encode and decode various formats' },
  { id: 'Security', name: 'Security', description: 'Password, hash, and JWT tools' },
  { id: 'Time & Date', name: 'Time & Date', description: 'Timestamp and date converters' },
  { id: 'Generators', name: 'Generators', description: 'Generate IDs, codes, and more' },
  { id: 'Text Tools', name: 'Text Tools', description: 'Text manipulation and analysis' },
  { id: 'QA & Compare', name: 'QA & Compare', description: 'Compare and validate' },
  { id: 'Utilities', name: 'Utilities', description: 'General utility tools' },
  { id: 'CSS Generators', name: 'CSS Generators', description: 'Generate CSS code and styles' },
  { id: 'Converters', name: 'Converters', description: 'Convert between data formats' },
  { id: 'Minifiers', name: 'Minifiers', description: 'Minify and compress code' },
  { id: 'Calculators', name: 'Calculators', description: 'Calculate values and convert units' },
];
